INSERT INTO brands (name, slug, country) VALUES
('Mercedes-Benz','mercedes-benz','Germany'),
('BMW','bmw','Germany'),
('Audi','audi','Germany'),
('Volkswagen','volkswagen','Germany'),
('Porsche','porsche','Germany'),
('Opel','opel','Germany'),
('Ford','ford','USA'),
('Tesla','tesla','USA'),
('Toyota','toyota','Japan'),
('Honda','honda','Japan'),
('Nissan','nissan','Japan'),
('Mazda','mazda','Japan'),
('Hyundai','hyundai','South Korea'),
('Kia','kia','South Korea'),
('Volvo','volvo','Sweden'),
('Peugeot','peugeot','France'),
('Renault','renault','France'),
('Citroën','citroen','France'),
('Fiat','fiat','Italy'),
('Skoda','skoda','Czech Republic');